

/*
 * Created on Fri Sep 17 14:59:59 ART 2010
 *
 * Generated by GEMS 
 */
 
package org.gems.test.deployment.deployment;


import org.eclipse.gmt.gems.model.Atom;
import org.eclipse.gmt.gems.model.Model;
import org.eclipse.gmt.gems.model.Visitor;

/**
 * 
 */
 
public interface DeploymentVisitor extends Visitor{
    public static final String MODEL_ID = "http://www.sf.net/projects/gems/dsml/deployment";
    
	
	


	   public void visitDeploymentPlan(DeploymentPlan tovisit);
	 
	   public void visitComponent(Component tovisit);
	 
	   public void visitNode(Node tovisit);
	 
	   public void visitNodeResource(NodeResource tovisit);
	 
	   public void visitComponentProperty(ComponentProperty tovisit);
	 
}

