  


/*
 * Created on Fri Sep 17 14:59:59 ART 2010
 *
 * Generated by GEMS 
 */
 
package org.gems.test.deployment.deployment;



public interface EMFModelObject {
	public org.gems.test.deployment.emf.deployment.ModelObject getEMFObject();
}