  


/*
 * Created on Fri Sep 17 14:59:59 ART 2010
 *
 * Generated by GEMS 
 */
 
package org.gems.test.deployment.deployment;


import org.eclipse.gmt.gems.model.ModelObject;
import org.eclipse.gmt.gems.ModelRepository;
import org.eclipse.emf.common.util.EList;
import org.eclipse.gmt.gems.model.Container;
import org.eclipse.gmt.gems.model.ModelObject;
import org.eclipse.gmt.gems.model.event.ModelChangeEvent;

public class EMFSubtypeImpl extends org.eclipse.gmt.gems.SubtypeImpl {
	public class EMFInstanceUpdater extends InstanceUpdater{
		private org.gems.test.deployment.emf.deployment.SubtypeLink link_;
		
		public EMFInstanceUpdater(ModelObject base, ModelObject m) {
			super(base, m);
			link_ = org.gems.test.deployment.emf.deployment.impl.DeploymentFactoryImpl.eINSTANCE.createSubtypeLink();
			link_.setBase(((EMFModelObject)base).getEMFObject());
			link_.setInstance(((EMFModelObject)m).getEMFObject());
			getModel().getLinks().add(link_);
		}
		
		public EMFInstanceUpdater(ModelObject base, ModelObject m, org.gems.test.deployment.emf.deployment.SubtypeLink link) {
			super(base, m);
			link_ = link;
		}
		

		@Override
		public void unRegister() {
			getModel().getLinks().remove(link_);
			super.unRegister();
		}
		
	}
    org.gems.test.deployment.emf.deployment.Subtype model_;

	public EMFSubtypeImpl(ModelObject obj, String name){
		super(obj,name);
		register();
	}
	
	public EMFSubtypeImpl(ModelObject obj, org.gems.test.deployment.emf.deployment.Subtype emfobj, String name){
		super(obj,name);
		model_ = emfobj;
		
	}
	
	public void createUpdater(ModelObject base, ModelObject cop){
		new EMFInstanceUpdater(base,cop);
	}
	
	public void createUpdater(ModelObject base, ModelObject cop, org.gems.test.deployment.emf.deployment.SubtypeLink link){
		new EMFInstanceUpdater(base,cop,link);
	}
	
	public void addInstance(ModelObject subt){
		addInstance(subt,true);
	}
	
	public void addInstance(ModelObject subt, boolean modifymodel){
		if(modifymodel)
			getModel().getInstances().add(((org.gems.test.deployment.deployment.EMFModelObject)subt).getEMFObject());
		super.addInstance(subt);
	}
	
	public void removeInstance(ModelObject subt){
		getModel().getInstances().remove(((org.gems.test.deployment.deployment.EMFModelObject)subt).getEMFObject());
		super.removeInstance(subt);
	}
	
	public void unRegister(){
		Root root = (Root)ModelRepository.getInstance().getInstanceRepository().getInstance(getBase().getModelInstanceID()).getRoot();
		if(root != null)
			root.getEMFObject().getSubtypes().remove(getModel());
	}
	
	public void register(){
		Root root = (Root)ModelRepository.getInstance().getInstanceRepository().getInstance(getBase().getModelInstanceID()).getRoot();
		if(root != null && !root.getEMFObject().getSubtypes().contains(getModel()))
			root.getEMFObject().getSubtypes().add(getModel());
	}
	
    public org.gems.test.deployment.emf.deployment.Subtype getModel(){
		if(model_ == null){
			model_ = org.gems.test.deployment.emf.deployment.impl.DeploymentFactoryImpl.eINSTANCE.createSubtype();
			model_.setBase(((org.gems.test.deployment.deployment.EMFModelObject)getBase()).getEMFObject());
			//model_.eAdapters().add(this);
			model_.setName(getName());
			register();
		}
		return model_;
	}
}