

/*
 * Created on Fri Sep 17 14:59:59 ART 2010
 *
 * Generated by GEMS 
 */
 
package org.gems.test.deployment.deployment;

import java.util.Hashtable;
import org.eclipse.swt.graphics.Color;
import org.eclipse.gmt.gems.model.ConnectionDecoration;
import org.eclipse.draw2d.ColorConstants;
import org.eclipse.gmt.gems.model.ConnectionAppearance;
import org.eclipse.gmt.gems.figures.Hints;
import org.eclipse.gmt.gems.Aspect;
import org.eclipse.gmt.gems.ModelProvider;
import org.eclipse.gmt.gems.model.ModelObject;
import org.eclipse.swt.widgets.Display;

public class GraphicsProviderImpl extends org.eclipse.gmt.gems.model.GraphicsProviderImpl {
   
    public String getModelID() {
        return DeploymentProvider.MODEL_ID;
    }
   
    protected void createAspects() {
     super.createAspects();
    }
   
    protected void createConnectionAppearances() {
        	ConnectionAppearance Deploymentattr = new ConnectionAppearance(
                ConnectionAppearance.NONE,
                ConnectionAppearance.ARROW,
                Hints.getColor("(0,0,0)"),
                0,
                1
              );
        	connectionAppearances_.put(DeploymentConnectionType.INSTANCE,Deploymentattr);
             
        super.createConnectionAppearances();
    }
    protected void createConnectionDecorations() {
        
        super.createConnectionDecorations();
    }
    
    protected void createDrawingHints() {
    	
    	Hashtable DeploymentPlan_hints = new Hashtable(7);
    	
		
		DeploymentPlan_hints.put("background-color", "(255,255,255)");
		
		
		DeploymentPlan_hints.put("draw-name", "true");
		
		
		DeploymentPlan_hints.put("draw-type", "true");
		
		
		DeploymentPlan_hints.put("label-font", "default");
		
		
		DeploymentPlan_hints.put("label-fontsize", "10");
		
		
		DeploymentPlan_hints.put("label-fontstyle", "normal");
		
		
		DeploymentPlan_hints.put("label-foreground", "(0,0,0)");
		
		
		DeploymentPlan_hints.put("label-background", "(255,255,255)");
		
		drawingHints_.put(DeploymentPlan.class, DeploymentPlan_hints);
		
    	Hashtable Component_hints = new Hashtable(7);
    	
		
		Component_hints.put("background-color", "(255,255,255)");
		
		
		Component_hints.put("draw-name", "true");
		
		
		Component_hints.put("draw-type", "true");
		
		
		Component_hints.put("label-font", "default");
		
		
		Component_hints.put("label-fontsize", "10");
		
		
		Component_hints.put("label-fontstyle", "normal");
		
		
		Component_hints.put("label-foreground", "(0,0,0)");
		
		
		Component_hints.put("label-background", "(255,255,255)");
		
		drawingHints_.put(Component.class, Component_hints);
		
    	Hashtable Node_hints = new Hashtable(7);
    	
		
		Node_hints.put("background-color", "(255,255,255)");
		
		
		Node_hints.put("draw-name", "true");
		
		
		Node_hints.put("draw-type", "true");
		
		
		Node_hints.put("label-font", "default");
		
		
		Node_hints.put("label-fontsize", "10");
		
		
		Node_hints.put("label-fontstyle", "normal");
		
		
		Node_hints.put("label-foreground", "(0,0,0)");
		
		
		Node_hints.put("label-background", "(255,255,255)");
		
		drawingHints_.put(Node.class, Node_hints);
		
    	Hashtable NodeResource_hints = new Hashtable(7);
    	
		
		NodeResource_hints.put("background-color", "(255,255,255)");
		
		
		NodeResource_hints.put("draw-name", "true");
		
		
		NodeResource_hints.put("draw-type", "true");
		
		
		NodeResource_hints.put("label-font", "default");
		
		
		NodeResource_hints.put("label-fontsize", "10");
		
		
		NodeResource_hints.put("label-fontstyle", "normal");
		
		
		NodeResource_hints.put("label-foreground", "(0,0,0)");
		
		
		NodeResource_hints.put("label-background", "(255,255,255)");
		
		drawingHints_.put(NodeResource.class, NodeResource_hints);
		
    	Hashtable ComponentProperty_hints = new Hashtable(7);
    	
		
		ComponentProperty_hints.put("background-color", "(255,255,255)");
		
		
		ComponentProperty_hints.put("draw-name", "true");
		
		
		ComponentProperty_hints.put("draw-type", "true");
		
		
		ComponentProperty_hints.put("label-font", "default");
		
		
		ComponentProperty_hints.put("label-fontsize", "10");
		
		
		ComponentProperty_hints.put("label-fontstyle", "normal");
		
		
		ComponentProperty_hints.put("label-foreground", "(0,0,0)");
		
		
		ComponentProperty_hints.put("label-background", "(255,255,255)");
		
		drawingHints_.put(ComponentProperty.class, ComponentProperty_hints);
		
		super.createDrawingHints();
	}
    
    public ModelProvider getModelProvider() {
        return DeploymentProvider.getInstance();
    }
}


