

/*
 * Created on Fri Sep 17 14:59:59 ART 2010
 *
 * Generated by GEMS 
 */
 
package org.gems.test.deployment.deployment;

import org.eclipse.gmt.gems.LabelProvider;


public class LabelProviderImpl implements LabelProvider {

	/**
	 * 
	 */
	public LabelProviderImpl() {
		super();
		
	}

	/* (non-Javadoc)
	 * @see org.eclipse.gmt.gems.LabelProvider#getLabel(java.lang.Object)
	 */
	public String getLabel(Object key) {
		String name = key.getClass().getName();
		return key.getClass().getName().substring(name.lastIndexOf(".")+1);
	}

	/* (non-Javadoc)
	 * @see org.eclipse.gmt.gems.LabelProvider#getDescription(java.lang.Object)
	 */
	public String getDescription(Object key) {
		// TODO Auto-generated method stub
		return "";
	}

}
