

/*
 * Created on Fri Sep 17 14:59:59 ART 2010
 *
 * Generated by GEMS 
 */
 
package org.gems.test.deployment.deployment;


import java.io.File;
import java.util.Vector;
import java.util.LinkedList;
import java.util.List;
import java.util.Hashtable;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.emf.ecore.xmi.impl.XMIResourceFactoryImpl;
import org.eclipse.gmt.gems.ModelInstance;
import org.eclipse.gmt.gems.ModelInstanceRepository;
import org.eclipse.gmt.gems.ModelRepository;
import org.eclipse.gmt.gems.ModelSerializer;
import org.eclipse.gmt.gems.InstanceListener;
import org.eclipse.gmt.gems.model.ModelObject;
import org.eclipse.gmt.gems.model.Root;
import org.eclipse.gmt.gems.model.Visitor;
import org.eclipse.gmt.gems.model.actions.EventInterestFactory;
import org.eclipse.gmt.gems.model.actions.EventInterestFactoryRepository;
import org.eclipse.gmt.gems.model.actions.ModelActionRegistry;
import org.eclipse.gmt.gems.model.actions.ModelActionResult;
import org.eclipse.gmt.gems.model.actions.ModelEventInterest;
import org.eclipse.gmt.gems.model.actions.PersistentModelEventInterest;
import org.eclipse.gmt.gems.model.actions.VisitorInterpreter;
import org.eclipse.emf.common.util.EList;
import org.gems.test.deployment.emf.deployment.*;

public class Serializer implements ModelSerializer{
	
	
	public void serializeModel(ModelInstance inst,IFile file, IProgressMonitor monitor) throws Exception{
		serializeToXMI(inst.getRoot(),file);
	}
	public ModelInstance readModel(IFile dest, ClassLoader cl, IProgressMonitor monitor) throws Exception{
		GemsFactory factory = new GemsFactory();
		ResourceSet resourceSet = new ResourceSetImpl();

		
		resourceSet.getPackageRegistry().put(org.gems.test.deployment.emf.deployment.impl.DeploymentPackageImpl.eINSTANCE.getNsURI(),org.gems.test.deployment.emf.deployment.impl.DeploymentPackageImpl.eINSTANCE);
		

	    resourceSet.getResourceFactoryRegistry().getExtensionToFactoryMap().put("dmod", 
		new XMIResourceFactoryImpl());
		
		File f = ModelInstanceRepository.getFile(dest);
		Resource resource = resourceSet.createResource(URI.createFileURI(f.getAbsolutePath()));
		
		ModelInstance inst = null;

		resource.load(null);
		EList contents = resource.getContents();
		org.gems.test.deployment.deployment.Root root = null;
		if(contents.size() > 0){
			org.gems.test.deployment.emf.deployment.Root eroot = (org.gems.test.deployment.emf.deployment.Root)contents.get(0);
			inst = factory.loadModel(eroot);
			
			List<EventInterestFactory> facts = EventInterestFactoryRepository.getInstance().getEventInterestFactories(inst.getRoot().getModelID());
			
			ModelActionRegistry mar = new ModelActionRegistry();
			inst.addInstanceListener(mar);
			EList mementos = eroot.getMementos();
		
			for(Object m : mementos){
				Memento memento = (Memento)m;
				try{
					EventInterestFactory fact = EventInterestFactoryRepository.getInstance().getFactoryByID(memento.getId());
					if(fact != null){
						MementoImpl mimpl = new MementoImpl(memento);
						PersistentModelEventInterest pei = fact.loadInterest(mimpl);
						if(pei != null)
							mar.addInterest(pei);
					}
				}catch (Exception e) {
				}
			}
			
			root = (org.gems.test.deployment.deployment.Root)inst.getRoot();
			DeploymentPlan rr = null;
			if(eroot.getRealRoot() != null)
				rr = (DeploymentPlan)factory.getPart(eroot.getRealRoot());
			if(rr == null)
			   rr = new DeploymentPlan();
		    root.setRealRoot(rr);
			
			eroot.getMementos().clear();
		} else {
			inst = ModelRepository.getInstance().getInstanceRepository().getInstance(root.getModelInstanceID());
			root = new org.gems.test.deployment.deployment.Root();
			
		    root.setRealRoot(new DeploymentPlan());
			
			inst.setRoot(root);
		}

		
		
		return inst;
	}
	
	public String getType(){
		return "Deployment to XMI";
	}
	public String getFileExtension(){
		return "dmod";
	}

	
	public void serializeToXMI(ModelObject obj, IFile dest) {
		
		try{

		ResourceSet resourceSet = new ResourceSetImpl();

		ModelInstance inst = ModelRepository.getInstance().getInstanceRepository().getInstance(obj.getModelInstanceID());
		org.gems.test.deployment.deployment.Root root = (org.gems.test.deployment.deployment.Root)ModelRepository.getInstance().getInstanceRepository().getInstance(obj.getModelInstanceID()).getRoot();
		
		LinkedList<PersistentModelEventInterest> peis = new LinkedList<PersistentModelEventInterest>();
		List<InstanceListener> listens = inst.getInstanceListeners();
		for(InstanceListener l : listens){
			if(l instanceof ModelActionRegistry){
				ModelActionRegistry mar = (ModelActionRegistry)l;
				for(ModelEventInterest ei : mar.getInterests()){
					if(ei instanceof PersistentModelEventInterest){
						peis.add((PersistentModelEventInterest)ei);
					}
				}
			}
		}
		for(PersistentModelEventInterest pei : peis){
		    try{
			MementoImpl memento = new MementoImpl();
			memento.setId(pei.getFactoryID());
			pei.saveState(memento);
			root.getModel().getMementos().add(memento.getModel());
			}catch(Throwable whoops){
			 
			}
		}
		
		resourceSet.getPackageRegistry().put(org.gems.test.deployment.emf.deployment.impl.DeploymentPackageImpl.eINSTANCE.getNsURI(),org.gems.test.deployment.emf.deployment.impl.DeploymentPackageImpl.eINSTANCE);
		

		resourceSet.getResourceFactoryRegistry().getExtensionToFactoryMap().put("dmod", 
		new XMIResourceFactoryImpl());
		
		File f = ModelInstanceRepository.getFile(dest);
		Resource resource = resourceSet.createResource(URI.createFileURI(f.getAbsolutePath()));

		resource.getContents().add(root.getEMFObject());

		resource.save(null);
		
		
		DeploymentPlan rr = root.getRealRoot();
		f = ModelInstanceRepository.getFile(dest);
		f = new File(f.getParentFile(),f.getName()+".gemx");
		resource = resourceSet.createResource(URI.createFileURI(f.getAbsolutePath()));
        resource.getContents().add(root.getRealRoot().getEMFObject());
		resource.save(null);
		root.setRealRoot(rr);

		
		}catch (Exception e) {
			e.printStackTrace();
		}
	}
}

